#!/bin/bash
DIR=/root/spaces/nodejs-formidable-demo
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/root/spaces/nodejs-formidable-demo/node_modules
NODE=/usr/bin/node

test -x $NODE || exit 0

function start_app {
  NODE_ENV=development nohup "$NODE" "$DIR/app.js" 1>>"$DIR/logs/nodejs-formidable-demo.log" 2>&1 &
  echo $! > "$DIR/pids/nodejs-formidable-demo.pid"
}

function stop_app {
  kill `cat $DIR/pids/nodejs-formidable-demo.pid`
}

case $1 in
  start)
    start_app ;;
  stop)
    stop_app ;;
  restart)
    stop_app
    start_app
    ;;
  *)
   echo "usage: clearstonecc {start|stop}" ;;
 
esac
exit 0
